version: "3"

services:
  web:
    image: yohanii/dicobot_prod:1.15
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - export_network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=chatbotdb
    ports:
      - "3306:3306"
    networks:
      - export_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  export_network:
    driver: bridge