spring:
  application:
    name: discordchatbot
  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query의 ?에 어떤 값이 들어가는지 추적할 수 있는 설정.

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}

quotes:
#  api-key: xVjJozFLj4NJrLJ7AmUlnhZMXSxouIKrKabu3uGa
  api-key: 7jXlg6Zmr9mKSwVRfGBc3ycTtkQY2ehOclLjeu5y