spring:
  application:
    name: discordchatbot

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query의 ?에 어떤 값이 들어가는지 추적할 수 있는 설정.

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}

quotes:
#  api-key: xVjJozFLj4NJrLJ7AmUlnhZMXSxouIKrKabu3uGa
  api-key: 7jXlg6Zmr9mKSwVRfGBc3ycTtkQY2ehOclLjeu5y